"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "cursorLocator/*.pot",
    "translation": "cursorLocator/locale/%two_letters_code%/LC_MESSAGES/nvda.po"
  },
  {
    "source": "cursorLocator/*.md",
    "translation": "cursorLocator/doc/%two_letters_code%/readme.md"
  },
]
