"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "cursorLocator/cursorLocator.pot",
    "translation": "cursorLocator/locale/%two_letters_code%/LC_MESSAGES/nvda.po"
  },
  {
    "source": "cursorLocator/readme.pot",
    "translation": "cursorLocator/translateDoc/%two_letters_code%/readme.po"
  },
]
