name: Import to crowdin

on:
  # push:
    # branches: [ main ]
  workflow_dispatch:

jobs:
  importToCrowdin:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install scons markdown
          sudo apt update
          sudo apt install gettext
          sudo apt install translate-toolkit
      - name: Create add-on
        run: scons
      - name: Create pot "file
        run: scons pot
      - name: Move addon folder
        run: |
          mkdir ${{ github.event.repository.name }}
          mv addon/locale ${{ github.event.repository.name }}
          mv addon/doc ${{ github.event.repository.name }}
          mv *.pot ${{ github.event.repository.name }}
          mv readme.md ${{ github.event.repository.name }}

      - name: Convert markdown to pot
        run: md2po -P ${{ github.event.repository.name }}/readme.md ${{ github.event.repository.name }}
      - name: Move po files in doc
        run: |
          for pofile in ${{ github.event.repository.name }}/*.po; do mv $pofile sed 's/\(.*\.\)\(.*\.\).*/\1\/readme.po/'; done;

      - name: list
        run: ls -R ${{  github.event.repository.name }}
      - name: Upload doc
        uses: actions/upload-artifact@v4
        with:
          name: translatedDoc
          path: ${{ github.event.repository.name }}/doc
